# .tools/abilities_gen.py
import sys, yaml, pathlib

CAT = pathlib.Path(".tools/abilities.yml")
ENB = pathlib.Path(".tools/abilities_enabled.yml")
OUT = pathlib.Path(".tools/abilities.mk")

def load_yaml(p):
    with p.open() as f:
        return yaml.safe_load(f)

def main():
    cat = load_yaml(CAT)
    enb = load_yaml(ENB)
    abil = cat.get("abilities", {})
    enabled = enb.get("enabled", [])
    lines = []
    lines.append("# AUTOGENERATED by .tools/abilities_gen.py")
    for name in enabled:
        a = abil.get(name)
        if not a: 
            continue
        lint     = a.get("lint","")
        validate = a.get("validate","")
        check    = a.get("check","")
        run      = a.get("run","")
        # Targets names: <ab>-lint / <ab>-validate / <ab>-check / <ab>-run
        if lint:
            lines.append(f"{name}-lint:\n\t{lint}")
        if validate:
            lines.append(f"{name}-validate:\n\t{validate}")
        if check:
            lines.append(f"{name}-check:\n\t{check}")
        if run:
            lines.append(f"{name}-run:\n\t{run}")
    OUT.write_text("\n\n".join(lines) + "\n")
    print(f"[abilities] generated {OUT}")

if __name__ == "__main__":
    main()
