# AUTOGENERATED by .tools/abilities_gen.py

ansible-lint:
	ansible-lint ansible/playbook.yml -v || true

ansible-check:
	ansible-playbook -i ansible/inventory.ini ansible/playbook.yml --check -vvv || true

ansible-run:
	ansible-playbook -i ansible/inventory.ini ansible/playbook.yml -vv

python-lint:
	ruff check src || true

python-validate:
	python -m pyflakes src || true

python-check:
	pytest -q || true

python-run:
	python -m src || true

terraform-lint:
	terraform -chdir=terraform fmt -check

terraform-validate:
	terraform -chdir=terraform validate -no-color

terraform-check:
	terraform -chdir=terraform plan -no-color -input=false -var="project=${TF_PROJECT:-llm-demo}" || true
